// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI5cnIjcr2Br_3F2cR4Ve34xZIKQJ9CZk',
    appId: '1:146266364801:web:0a4531c68a9eda839de680',
    messagingSenderId: '146266364801',
    projectId: 'todolist-b84ac',
    authDomain: 'todolist-b84ac.firebaseapp.com',
    storageBucket: 'todolist-b84ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDke6NIBbMqGXJO8OcAbULp-rJPWKe4so',
    appId: '1:146266364801:android:45d5cb683cb84c919de680',
    messagingSenderId: '146266364801',
    projectId: 'todolist-b84ac',
    storageBucket: 'todolist-b84ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZNCeuf2m5qF6OwOfA3nUO9GwIj8V48WQ',
    appId: '1:146266364801:ios:7cae1349ad556ffe9de680',
    messagingSenderId: '146266364801',
    projectId: 'todolist-b84ac',
    storageBucket: 'todolist-b84ac.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZNCeuf2m5qF6OwOfA3nUO9GwIj8V48WQ',
    appId: '1:146266364801:ios:28f5d91baa1d78fc9de680',
    messagingSenderId: '146266364801',
    projectId: 'todolist-b84ac',
    storageBucket: 'todolist-b84ac.appspot.com',
    iosBundleId: 'com.example.flutterApplication4.RunnerTests',
  );
}
